In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU: Tesla T4


# Creating a Tensor

In [4]:
# using empty

a = torch.empty(2,3)
print(a)

# It created a tensor, empty makes space in memory and displays preexisting values on that memory


tensor([[-2.2831e+02,  4.3201e-41, -2.2831e+02],
        [ 4.3201e-41,  0.0000e+00,  0.0000e+00]])


In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

# all zero initialized values

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)  #random values, usecase: to initialze random weights

tensor([[0.8907, 0.8078, 0.5303],
        [0.3887, 0.4037, 0.2339]])

In [9]:
# use of seed
torch.manual_seed(42)   # this is similar to random_state=42 in PyTorch to get same random values everytime
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])   # Custom tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways
# arange
print("using arange ->", torch.arange(0,18,2))

print("using linspace ->", torch.linspace(0,18,12))  # Linear spaced -> evenly spaced values

print("using eye ->", torch.eye(5))  #Identity matrix (Eyedentity Matrix xD)

print("using full ->", torch.full((4,3), 5))  # Fill the tensor

using arange -> tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])
using linspace -> tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)  # empty tensor with same shape of x

tensor([[0, 0, 0],
        [0, 1, 0]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x)
# this code did run because rand() generate random float values from 0-1, but our x has integers.
# To solve this we must explicitly tell to generate float values

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [18]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

# Tensor Data Types

In [19]:
# find data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
# using to() --> convert exisiting tensor to other dtype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

## Scalar Operation

In [23]:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [24]:
# addition
x + 1

tensor([[1.8694, 1.5677],
        [1.7411, 1.4294]])

In [25]:
# subtraction
x - 1

tensor([[-0.1306, -0.4323],
        [-0.2589, -0.5706]])

In [26]:
# multiplication
x * 3

tensor([[2.6082, 1.7031],
        [2.2233, 1.2882]])

In [27]:
# division
x / 2

tensor([[0.4347, 0.2839],
        [0.3705, 0.2147]])

In [28]:
# int division
(x*100) // 3

tensor([[28., 18.],
        [24., 14.]])

In [29]:
# mod
# modulo (%) returns the remainder of a division.
((x*100) // 3)%2

tensor([[0., 0.],
        [0., 0.]])

In [30]:
# power
x**2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

# Element Wise Operations

In [31]:
a = torch.rand(2,2)
b = torch.rand(2,2)

print(a)
print(b)

tensor([[0.8854, 0.5739],
        [0.2666, 0.6274]])
tensor([[0.2696, 0.4414],
        [0.2969, 0.8317]])


In [32]:
# add
print(a+b)

# sub
print(a-b)

#multiply
print(a*b)

#divide
print(a/b)

#power
print(a**b)

#mod
print(a%b)

tensor([[1.1551, 1.0153],
        [0.5635, 1.4591]])
tensor([[ 0.6158,  0.1325],
        [-0.0303, -0.2042]])
tensor([[0.2387, 0.2533],
        [0.0792, 0.5218]])
tensor([[3.2839, 1.3003],
        [0.8978, 0.7544]])
tensor([[0.9677, 0.7826],
        [0.6753, 0.6787]])
tensor([[0.0765, 0.1325],
        [0.2666, 0.6274]])


In [33]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [34]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [35]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [36]:
d = torch.tensor([1.9,2.3,3.7,4.3])
d

tensor([1.9000, 2.3000, 3.7000, 4.3000])

In [37]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [38]:
# ceil
# go to above number if decimal is greater than 0
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [39]:
#
# go to lower number that is its non decimal value integer
torch.floor(d)

tensor([1., 2., 3., 4.])

In [40]:
# clamp
# it scaled values in this min max range
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction Operation

In [41]:
e = torch.randint(size=(2,3), low=0, high=5)
e

tensor([[4, 3, 1],
        [4, 2, 4]])

In [42]:
# sum
torch.sum(e)

tensor(18)

In [43]:
# sum along columns
torch.sum(e, dim=0)

tensor([8, 5, 5])

In [44]:
# sum along rows
torch.sum(e, dim=1)

tensor([ 8, 10])

In [45]:
# mean
# mean function works only on float dtype
torch.mean(e.to(torch.float32))

tensor(3.)

In [46]:
e = e.to(torch.float32)

In [47]:
torch.mean(e, dim=0)

tensor([4.0000, 2.5000, 2.5000])

In [48]:
# median
torch.median(e)

tensor(3.)

In [49]:
# max and min
torch.max(e)

tensor(4.)

In [50]:
torch.min(e)

tensor(1.)

In [51]:
# product
torch.prod(e)

tensor(384.)

In [52]:
# std
torch.std(e)

tensor(1.2649)

In [53]:
# variance
torch.var(e)

tensor(1.6000)

In [54]:
e

tensor([[4., 3., 1.],
        [4., 2., 4.]])

In [55]:
# argmax --> tells the positions of biggest item in tensor
torch.argmax(e)

tensor(0)

In [56]:
# argmin
torch.argmin(e)

tensor(2)

# Matrix Operation

In [57]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 0, 5],
        [9, 3, 4]])
tensor([[9, 6],
        [2, 0],
        [6, 2]])


In [58]:
# Matrix Multiplication
torch.matmul(f,g)

tensor([[ 48,  22],
        [111,  62]])

In [59]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

print(vector1)
print(vector2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [60]:
# dot product
torch.dot(vector1, vector2)

tensor(32)

In [61]:
f

tensor([[2, 0, 5],
        [9, 3, 4]])

In [62]:
# Transpose
torch.transpose(f, 0, 1)

tensor([[2, 9],
        [0, 3],
        [5, 4]])

In [63]:
torch.transpose(f, 1, 0)

tensor([[2, 9],
        [0, 3],
        [5, 4]])

In [64]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[7., 9., 7.],
        [3., 3., 4.],
        [3., 7., 0.]])

In [65]:
# determinant
torch.det(h)

tensor(-4.0000)

In [66]:
# inverse
torch.inverse(h)

tensor([[  7.0000, -12.2500,  -3.7500],
        [ -3.0000,   5.2500,   1.7500],
        [ -3.0000,   5.5000,   1.5000]])

# Comparision Operaions

In [67]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 0, 9],
        [6, 9, 5]])
tensor([[4, 8, 8],
        [6, 0, 0]])


In [68]:
# greater than
i > j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [69]:
# less than
i < j

tensor([[False,  True, False],
        [False, False, False]])

In [70]:
# equal to
i == j

tensor([[False, False, False],
        [ True, False, False]])

In [71]:
# not equal to
i != j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [72]:
# greater than equal to
i >= j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [73]:
# less than equal to
i <= j

tensor([[False,  True, False],
        [ True, False, False]])

# Special Functions

In [74]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 0., 1.],
        [3., 0., 1.]])

In [75]:
# log
torch.log(k)

tensor([[  -inf,   -inf, 0.0000],
        [1.0986,   -inf, 0.0000]])

In [76]:
# exp
torch.exp(k)

tensor([[ 1.0000,  1.0000,  2.7183],
        [20.0855,  1.0000,  2.7183]])

In [77]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 0.0000, 1.0000],
        [1.7321, 0.0000, 1.0000]])

In [78]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.5000, 0.7311],
        [0.9526, 0.5000, 0.7311]])

In [79]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0474, 0.5000, 0.5000],
        [0.9526, 0.5000, 0.5000]])

In [80]:
# relu
torch.relu(k)

tensor([[0., 0., 1.],
        [3., 0., 1.]])

# Inplace Operations

In [82]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041]])
tensor([[0.1088, 0.1637, 0.7025],
        [0.6790, 0.9155, 0.2418]])


In [83]:
m + n
# with this type of addition we are storing the result in another locatin in memory

tensor([[0.3106, 1.1134, 1.3691],
        [1.6602, 1.0028, 0.2458]])

In [84]:
# But to store the addition in m itself, like inplace m, we do:
m.add_(n)

tensor([[0.3106, 1.1134, 1.3691],
        [1.6602, 1.0028, 0.2458]])

In [85]:
m # updated values with sum

tensor([[0.3106, 1.1134, 1.3691],
        [1.6602, 1.0028, 0.2458]])

In [86]:
n

tensor([[0.1088, 0.1637, 0.7025],
        [0.6790, 0.9155, 0.2418]])

In [88]:
m.sigmoid_() # here we did sigmoid on m and also stored values in m itself

tensor([[0.5770, 0.7528, 0.7972],
        [0.8403, 0.7316, 0.5612]])

In PyTorch just add underscore _ infront of function before brackets to make them INPLACE OPERATION

# Copying a Tensor

In [89]:
a = torch.rand(2,3)
a

tensor([[0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])

In [90]:
b = a

In [91]:
b

tensor([[0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])

In [94]:
a[0][0] = 0
a

tensor([[0.0000, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])

In [95]:
b

tensor([[0.0000, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])

In [96]:
id(a), id(b)

(132408015353840, 132408015353840)

Here if we use assignment operator to make a copy of tensors then both tensors will be saved in a same memory location, which makes an issue that if we update any value in one tensor then other will also get updated. Which is not desirable for us.

In [97]:
# To solve it we use clone()
b = a.clone()

In [98]:
a[0][0] = 222
a

tensor([[222.0000,   0.7653,   0.2979],
        [  0.8035,   0.3813,   0.7860]])

In [99]:
b

tensor([[0.0000, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])

In [101]:
# Here now with clone(), it made different memory allocations
id(a), id(b)

(132408015353840, 132408015355680)

# Tensor Operations on GPU

In [102]:
torch.cuda.is_available()

True

In [103]:
device = torch.device('cuda')

In [104]:
# creating a new tensor on GPU

# These tensors will be made on GPU's VRAM
torch.rand((2,3), device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [107]:
# moving an existing tensor to GPU

a = torch.rand((2,3)) # a in tensor made on CPU
a

tensor([[0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227]])

In [110]:
b = a.to(device)
b # this is on GPU now

tensor([[0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227]], device='cuda:0')

In [112]:
b + 5
# Now this tensor operation is done with GPU as b is on GPU

tensor([[5.8399, 5.1374, 5.2331],
        [5.9578, 5.3313, 5.3227]], device='cuda:0')

Tensor Performance of CPU vs GPU

In [119]:
import time

# Define size of matrics
size = 10000  # Large size for performance comparision

# Create random matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f}")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time1 = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize()  # Wait until all queued CUDA (GPU) operations are finished.
gpu_time = time.time() - start_time1

print(f"Time on CPU: {gpu_time:.4f}")

# Compare Results
print("\nSpeedup (CPU time / GPU time): ",cpu_time/gpu_time)

Time on CPU: 15.1268
Time on CPU: 0.5883

Speedup (CPU time / GPU time):  25.71373053477468


# Reshaping Tensors

In [120]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [123]:
# reshape
a.reshape(2,2,2,2)  # make sure product on shape must be same as product of earlier matrix

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [125]:
# flatten --> makes 1d tensor
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
b = torch.rand(2,3,4)
b

tensor([[[0.5337, 0.8178, 0.6843, 0.5847],
         [0.0527, 0.9003, 0.0905, 0.2821],
         [0.0202, 0.1308, 0.2312, 0.3182]],

        [[0.7317, 0.1154, 0.8547, 0.0989],
         [0.7764, 0.0465, 0.2677, 0.6947],
         [0.2277, 0.9441, 0.2425, 0.9436]]])

In [128]:
# permute
b.permute(2,1,0)

# here 2 is 4 of b, 1 is 3, and 0 is 2--> means its of dimenion (4,3,2)

tensor([[[0.5337, 0.7317],
         [0.0527, 0.7764],
         [0.0202, 0.2277]],

        [[0.8178, 0.1154],
         [0.9003, 0.0465],
         [0.1308, 0.9441]],

        [[0.6843, 0.8547],
         [0.0905, 0.2677],
         [0.2312, 0.2425]],

        [[0.5847, 0.0989],
         [0.2821, 0.6947],
         [0.3182, 0.9436]]])

In [129]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [135]:
# unsqueeze
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape
#adds a new dimension of size 1 at position dimension

torch.Size([1, 226, 226, 3])

In [136]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [137]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [138]:
c.unsqueeze(-1).shape

torch.Size([226, 226, 3, 1])

In [144]:
# squeeze
d = torch.rand(1,7)
d

tensor([[0.2158, 0.9227, 0.6268, 0.2001, 0.0705, 0.5308, 0.3565]])

In [145]:
d.squeeze(0)

tensor([0.2158, 0.9227, 0.6268, 0.2001, 0.0705, 0.5308, 0.3565])

In [146]:
d.squeeze().shape

torch.Size([7])

In [150]:
# Removes the dimension dim only if its size is 1

# NumPy and PyTorch

In [153]:
import numpy as np

In [154]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [155]:
b = a.numpy()  # Tensor --> NumPy array

In [156]:
b

array([1, 2, 3])

In [157]:
type(b)

numpy.ndarray

In [158]:
c = np.array([4,5,6])
c

array([4, 5, 6])

In [159]:
torch.from_numpy(c)  # NumPy --> Tensor

tensor([4, 5, 6])