# Libraries and Dataset

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
df.shape

(569, 33)

In [7]:
df.drop(columns=["id","Unnamed: 32"], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

# Scaling

In [9]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [10]:
X_train

array([[ 1.55769890e+00,  3.82155341e-02,  1.46617070e+00, ...,
         1.29053661e+00,  7.64319175e-01,  2.86558395e-01],
       [-4.51548450e-01, -9.67783275e-01, -5.19510658e-01, ...,
        -1.08990893e+00, -1.61690744e-04, -8.79088347e-01],
       [-7.80230449e-01, -1.45554027e+00, -7.45486089e-01, ...,
         2.73418139e-01,  7.06743210e-01,  4.29104029e-01],
       ...,
       [ 1.63772582e+00,  1.53119827e-01,  1.64031690e+00, ...,
         2.04926815e+00, -2.43260209e-01,  2.44894875e+00],
       [ 2.16075892e+00,  7.55781118e-01,  2.10885311e+00, ...,
         1.61464044e+00, -1.34520020e+00, -7.00502875e-01],
       [ 3.22997826e-01,  2.49576041e+00,  2.30976552e-01, ...,
        -7.13082225e-01,  5.30816651e-01, -1.21151552e+00]])

# Label Encoding

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,

# NumPy arrays to PyTorch tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
X_train_tensor

tensor([[ 1.5577e+00,  3.8216e-02,  1.4662e+00,  ...,  1.2905e+00,
          7.6432e-01,  2.8656e-01],
        [-4.5155e-01, -9.6778e-01, -5.1951e-01,  ..., -1.0899e+00,
         -1.6169e-04, -8.7909e-01],
        [-7.8023e-01, -1.4555e+00, -7.4549e-01,  ...,  2.7342e-01,
          7.0674e-01,  4.2910e-01],
        ...,
        [ 1.6377e+00,  1.5312e-01,  1.6403e+00,  ...,  2.0493e+00,
         -2.4326e-01,  2.4489e+00],
        [ 2.1608e+00,  7.5578e-01,  2.1089e+00,  ...,  1.6146e+00,
         -1.3452e+00, -7.0050e-01],
        [ 3.2300e-01,  2.4958e+00,  2.3098e-01,  ..., -7.1308e-01,
          5.3082e-01, -1.2115e+00]], dtype=torch.float64)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

*   We will make a simple NN with one hidden neuron.
*   But as our X has 30 features means we will have 30 weights from the input layer to hidden layer



In [34]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss(self, y_pred, y):  # y = true labels -> (train/val/test)
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7    # 1 * 10^-7 --> 0.0000001
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred)).mean()
    return loss


# Important Parameters

In [39]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [40]:
# create model
model = MySimpleNN(X_train_tensor)

# Define Loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)
  #print(y_pred)

  # Loss Calculation
  loss = model.loss(y_pred, y_train_tensor)
  #print(loss)

  # Backward Pass
  loss.backward()

  # Parameters Update
  # Now lets update weights & bias:
  # w_new = w_old - n.dL/dw_old
  # b_new = b_old - n.dL/db_old
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients --> Before running new epoch make gradients=0
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print loss in each epoch
  print(f"Epoch: {epoch}, Loss: {loss.item()}") # .item() converts a scalar tensor into a Python float and removes it from the computation graph, mainly for logging or monitoring.”

Epoch: 0, Loss: 3.399543984417704
Epoch: 1, Loss: 3.265944652188143
Epoch: 2, Loss: 3.1213384550949863
Epoch: 3, Loss: 2.9753502532727345
Epoch: 4, Loss: 2.8226291101464995
Epoch: 5, Loss: 2.6641870085099293
Epoch: 6, Loss: 2.499689493330023
Epoch: 7, Loss: 2.335330425500182
Epoch: 8, Loss: 2.174295101701658
Epoch: 9, Loss: 2.009629233767316
Epoch: 10, Loss: 1.8407962366112252
Epoch: 11, Loss: 1.6794008411093768
Epoch: 12, Loss: 1.5289740374395444
Epoch: 13, Loss: 1.3917688099452368
Epoch: 14, Loss: 1.2698005088438196
Epoch: 15, Loss: 1.1641720544818297
Epoch: 16, Loss: 1.0750639898954912
Epoch: 17, Loss: 1.0019551368786435
Epoch: 18, Loss: 0.9435981370755909
Epoch: 19, Loss: 0.8980373908680788
Epoch: 20, Loss: 0.8628627692668009
Epoch: 21, Loss: 0.8356332116340198
Epoch: 22, Loss: 0.8142328028796829
Epoch: 23, Loss: 0.7970234385947628
Epoch: 24, Loss: 0.7828307864978552


In [41]:
model.weights

tensor([[ 0.1704],
        [-0.1386],
        [ 0.3198],
        [ 0.0097],
        [-0.1634],
        [-0.3401],
        [ 0.2334],
        [ 0.1779],
        [-0.2434],
        [ 0.1873],
        [-0.2834],
        [ 0.2534],
        [ 0.2259],
        [-0.2402],
        [ 0.3097],
        [ 0.1820],
        [-0.3313],
        [-0.1226],
        [ 0.0061],
        [-0.0584],
        [ 0.0564],
        [ 0.5400],
        [-0.3423],
        [-0.1820],
        [ 0.3465],
        [-0.1473],
        [ 0.0996],
        [-0.0797],
        [ 0.2061],
        [ 0.4009]], dtype=torch.float64, requires_grad=True)

In [42]:
model.bias

tensor([-0.1966], dtype=torch.float64, requires_grad=True)

# Evaluation

In [47]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
# But to calculate accuracy we must make them into 0s and 1s and compare with y_test.
  y_pred = (y_pred > 0.5).float()
# accuracy
accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5083102583885193
