<a href="https://colab.research.google.com/github/tanishqbololu/PyTorch/blob/main/5_pytorch_training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries and Dataset

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=["id","Unnamed: 32"], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

# Scaling

In [6]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [7]:
X_train

array([[-0.34226151,  0.69133691, -0.24880081, ...,  1.30425487,
         0.81088425,  2.39242699],
       [ 1.54703249, -0.11583605,  1.52773461, ...,  1.43147271,
         0.58286037,  0.37294981],
       [-0.09073674, -0.14803099, -0.1049031 , ...,  0.2420625 ,
        -0.09150811,  0.3859368 ],
       ...,
       [ 1.3097989 ,  0.21301219,  1.27892012, ...,  0.55780799,
        -0.91304093, -0.56447485],
       [ 0.0235927 , -1.48182107, -0.0509933 , ..., -0.82319537,
        -1.30278387, -0.76400227],
       [ 3.82790483,  1.59739431,  3.96611655, ...,  2.29747371,
        -0.42788375, -0.56093294]])

# Label Encoding

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
y_train

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,

# NumPy arrays to PyTorch tensors

In [10]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
X_train_tensor

tensor([[-0.3423,  0.6913, -0.2488,  ...,  1.3043,  0.8109,  2.3924],
        [ 1.5470, -0.1158,  1.5277,  ...,  1.4315,  0.5829,  0.3729],
        [-0.0907, -0.1480, -0.1049,  ...,  0.2421, -0.0915,  0.3859],
        ...,
        [ 1.3098,  0.2130,  1.2789,  ...,  0.5578, -0.9130, -0.5645],
        [ 0.0236, -1.4818, -0.0510,  ..., -0.8232, -1.3028, -0.7640],
        [ 3.8279,  1.5974,  3.9661,  ...,  2.2975, -0.4279, -0.5609]],
       dtype=torch.float64)

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

*   We will make a simple NN with one hidden neuron.
*   But as our X has 30 features means we will have 30 weights from the input layer to hidden layer



In [28]:
X_train.dtype, y_train.dtype

(dtype('float64'), dtype('int64'))

The model weigts are in float32, so we must either convert training data to floar32 with .float() or double the model with .double() to make it float64.
But doubling the model will make it occupy more space in memory unnecessarily.

In [23]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [14]:
import torch.nn as nn

In [40]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self, y_pred, y):  # y = true labels -> (train/val/test)
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7    # 1 * 10^-7 --> 0.0000001
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred)).mean()
    return loss


# Important Parameters

In [41]:
learning_rate = 0.1
epochs = 25

In [42]:
# define loss function
loss_function = nn.BCELoss()  # Binary Cross Entropy Loss

# Training Pipeline

In [43]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define Loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)
  #print(y_pred)

  # Zero Gradients --> Before running new epoch make gradients=0
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()
  optimizer.zero_grad()  #automatically makes all grads zero

  # Loss Calculation
  #loss = model.loss_function(y_pred, y_train_tensor)
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))  # This is loss fucntion made with nn.BCELoss()
  #print(loss)

  # Backward Pass
  loss.backward()

  # Parameters Update -> update weights & bias:
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad   # w_new = w_old - n.dL/dw_old
  #   model.linear.bias -= learning_rate * model.linear.bias.grad       # b_new = b_old - n.dL/db_old

  optimizer.step()  # -> this will automatically update the weights and bias

  # Print loss in each epoch
  print(f"Epoch: {epoch}, Loss: {loss.item()}") # .item() converts a scalar tensor into a Python float and removes it from the computation graph, mainly for logging or monitoring.”

Epoch: 0, Loss: 0.7081269025802612
Epoch: 1, Loss: 0.5338970422744751
Epoch: 2, Loss: 0.43957099318504333
Epoch: 3, Loss: 0.38159704208374023
Epoch: 4, Loss: 0.34234824776649475
Epoch: 5, Loss: 0.31390517950057983
Epoch: 6, Loss: 0.2922437787055969
Epoch: 7, Loss: 0.27511513233184814
Epoch: 8, Loss: 0.26116734743118286
Epoch: 9, Loss: 0.2495400607585907
Epoch: 10, Loss: 0.2396600842475891
Epoch: 11, Loss: 0.23113109171390533
Epoch: 12, Loss: 0.22367016971111298
Epoch: 13, Loss: 0.21706993877887726
Epoch: 14, Loss: 0.21117490530014038
Epoch: 15, Loss: 0.2058660387992859
Epoch: 16, Loss: 0.20105059444904327
Epoch: 17, Loss: 0.1966552734375
Epoch: 18, Loss: 0.19262118637561798
Epoch: 19, Loss: 0.18890050053596497
Epoch: 20, Loss: 0.1854538917541504
Epoch: 21, Loss: 0.18224874138832092
Epoch: 22, Loss: 0.17925763130187988
Epoch: 23, Loss: 0.17645743489265442
Epoch: 24, Loss: 0.17382843792438507


In [44]:
model.linear.weight

Parameter containing:
tensor([[ 0.3664,  0.0207,  0.3613,  0.2044,  0.0132,  0.0987,  0.0790,  0.3989,
          0.1084, -0.0227,  0.2973,  0.0102,  0.2258,  0.1983, -0.0913,  0.0885,
          0.0139, -0.0208,  0.0833, -0.1612,  0.3192,  0.3412,  0.1589,  0.1568,
          0.2192,  0.1289,  0.0832,  0.2690,  0.1293,  0.1214]],
       requires_grad=True)

In [45]:
model.linear.bias

Parameter containing:
tensor([-0.1018], requires_grad=True)

# Evaluation

In [32]:
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

In [46]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
# But to calculate accuracy we must make them into 0s and 1s and compare with y_test.
  y_pred = (y_pred > 0.5).float()
# accuracy
accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5186210870742798
