<a href="https://colab.research.google.com/github/tanishqbololu/PyTorch/blob/main/7_pytorch_training_pipeline_using_dataset_and_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries and Dataset

In [83]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [84]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [85]:
df.shape

(569, 33)

In [86]:
df.drop(columns=["id","Unnamed: 32"], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [87]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

# Scaling

In [88]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [89]:
X_train

array([[-1.50591627, -0.56922028, -1.4817654 , ..., -1.71316083,
        -0.72744587,  0.29925315],
       [ 1.5645063 ,  1.37721084,  1.53580226, ...,  0.89942079,
         0.64633222,  0.06750198],
       [-1.23208878, -0.24481509, -1.2624666 , ..., -1.71316083,
        -1.58366105, -1.03679233],
       ...,
       [ 1.75613   ,  0.51683186,  1.62014796, ...,  0.46650455,
        -1.05811106, -0.70770567],
       [ 0.01763097,  2.01896892,  0.01557151, ..., -0.47339129,
        -1.61401196, -0.32010184],
       [ 0.2314719 ,  1.39601693,  0.13566372, ..., -1.27587017,
        -2.13317229, -1.64803604]])

# Label Encoding

In [90]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [91]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,

# NumPy arrays to PyTorch tensors

In [92]:
# float32 because In PyTorch, neural network (nn) parameters and gradients default to float32.
X_train_tensor = torch.tensor(X_train)
X_test_tensor = torch.tensor(X_test)
y_train_tensor = torch.tensor(y_train)
y_test_tensor = torch.tensor(y_test)

In [93]:
X_train_tensor

tensor([[-1.5059, -0.5692, -1.4818,  ..., -1.7132, -0.7274,  0.2993],
        [ 1.5645,  1.3772,  1.5358,  ...,  0.8994,  0.6463,  0.0675],
        [-1.2321, -0.2448, -1.2625,  ..., -1.7132, -1.5837, -1.0368],
        ...,
        [ 1.7561,  0.5168,  1.6201,  ...,  0.4665, -1.0581, -0.7077],
        [ 0.0176,  2.0190,  0.0156,  ..., -0.4734, -1.6140, -0.3201],
        [ 0.2315,  1.3960,  0.1357,  ..., -1.2759, -2.1332, -1.6480]],
       dtype=torch.float64)

In [94]:
X_train_tensor.shape

torch.Size([455, 30])

In [95]:
y_train_tensor.shape

torch.Size([455])

# Dataset & DataLoader

In [104]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, lables):
    self.features = features.float()
    self.lables = lables.float()
    # we need to convert float64 to float32 because pyTorch models give weights in flaot32
    # if different dtypes then no matmul and no weight updations

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.lables[idx]

In [105]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [106]:
train_dataset[10]

(tensor([-0.2823,  0.3476, -0.2483, -0.3377, -0.6940,  0.0937,  0.2352, -0.3566,
         -0.8988, -0.3646, -0.3498, -0.7823, -0.2904, -0.2998,  0.0500,  0.3620,
          0.4588,  0.1288, -0.6051, -0.2024, -0.3129, -0.0288, -0.1969, -0.3453,
          0.1041,  0.6695,  0.8654,  0.0683, -0.5390, -0.1011]),
 tensor(0.))

In [113]:
train_dataset[10]

(tensor([-0.2823,  0.3476, -0.2483, -0.3377, -0.6940,  0.0937,  0.2352, -0.3566,
         -0.8988, -0.3646, -0.3498, -0.7823, -0.2904, -0.2998,  0.0500,  0.3620,
          0.4588,  0.1288, -0.6051, -0.2024, -0.3129, -0.0288, -0.1969, -0.3453,
          0.1041,  0.6695,  0.8654,  0.0683, -0.5390, -0.1011]),
 tensor(0.))

In [112]:
train_dataset[10][0].dtype

torch.float32

In [114]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Defining the model

*   We will make a simple NN with one hidden neuron.
*   But as our X has 30 features means we will have 30 weights from the input layer to hidden layer



In [115]:
import torch.nn as nn

In [116]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self, y_pred, y):  # y = true labels -> (train/val/test)
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7    # 1 * 10^-7 --> 0.0000001
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred)).mean()
    return loss


# Important Parameters

In [117]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [122]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()  # Binary Cross Entropy Loss

# Define Loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # Forward Pass
    y_pred = model(batch_features)
    #print(y_pred)

    # Zero Gradients --> Before running new epoch make gradients=0
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    optimizer.zero_grad()  #automatically makes all grads zero

    # Loss Calculation
    #loss = model.loss_function(y_pred, y_train_tensor)
    loss = loss_function(y_pred, batch_labels.view(-1,1))  # This is loss fucntion made with nn.BCELoss()
    #print(loss)

    # Backward Pass
    loss.backward()

    # Parameters Update -> update weights & bias:
    # with torch.no_grad():
    #   model.linear.weight -= learning_rate * model.linear.weight.grad   # w_new = w_old - n.dL/dw_old
    #   model.linear.bias -= learning_rate * model.linear.bias.grad       # b_new = b_old - n.dL/db_old

    optimizer.step()  # -> this will automatically update the weights and bias

    # Print loss in each epoch
    print(f"Epoch: {epoch}, Loss: {loss.item()}") # .item() converts a scalar tensor into a Python float and removes it from the computation graph, mainly for logging or monitoring.”

Epoch: 0, Loss: 0.7771965861320496
Epoch: 0, Loss: 0.45878204703330994
Epoch: 0, Loss: 0.46701183915138245
Epoch: 0, Loss: 0.4069208800792694
Epoch: 0, Loss: 0.283588707447052
Epoch: 0, Loss: 0.35568857192993164
Epoch: 0, Loss: 0.30755531787872314
Epoch: 0, Loss: 0.274344801902771
Epoch: 0, Loss: 0.2072087973356247
Epoch: 0, Loss: 0.20172002911567688
Epoch: 0, Loss: 0.22052724659442902
Epoch: 0, Loss: 0.20848579704761505
Epoch: 0, Loss: 0.25504904985427856
Epoch: 0, Loss: 0.30070191621780396
Epoch: 0, Loss: 0.20285211503505707
Epoch: 1, Loss: 0.25912997126579285
Epoch: 1, Loss: 0.10874348878860474
Epoch: 1, Loss: 0.17360180616378784
Epoch: 1, Loss: 0.1583614945411682
Epoch: 1, Loss: 0.16059142351150513
Epoch: 1, Loss: 0.18554344773292542
Epoch: 1, Loss: 0.2042340785264969
Epoch: 1, Loss: 0.234697163105011
Epoch: 1, Loss: 0.1407434046268463
Epoch: 1, Loss: 0.1400676816701889
Epoch: 1, Loss: 0.2581188678741455
Epoch: 1, Loss: 0.1592985987663269
Epoch: 1, Loss: 0.13807523250579834
Epoch: 

In [120]:
model.linear.weight

Parameter containing:
tensor([[ 0.7346,  0.6212,  0.4476,  0.4321,  0.2473,  0.0876,  0.3348,  0.5438,
          0.0963, -0.2179,  0.6288, -0.0517,  0.5175,  0.5698,  0.1458, -0.3415,
         -0.1512,  0.1746, -0.1003, -0.3302,  0.5218,  0.7561,  0.8221,  0.4629,
          0.4734,  0.3035,  0.5427,  0.6344,  0.2916,  0.2325]],
       requires_grad=True)

In [121]:
model.linear.bias

Parameter containing:
tensor([-0.2610], requires_grad=True)

# Evaluation

In [124]:
# Model evaluation using test_loader
model.eval()         # set model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float() # Convert probabilities to binary predictions

    # Calculate accuracy for current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean()
    accuracy_list.append(batch_accuracy.item())

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy}")


Accuracy: 0.9704861044883728
